require "test_helper"

class HomeControllerTest < ActionDispatch::IntegrationTest
  test "should get index" do
    get "/"
    assert_response :success
  end

  test "should create a new user and return created status" do
    get "/"
    assert_response :created
    assert_includes @response.body, "id"
  end

  test "should return error when user cannot be created" do
    User.stubs(:fresh).returns(User.new(name: "AutoGeneratedName"))
    User.any_instance.stubs(:save).returns(false)
      
    get "/"
    assert_response :unprocessable_entity
    assert_includes @response.body, "Could not create a new user."
  end
end